[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
NODE_ENV = "production"
AUTH_SECRET = "yVIXGr7GRlLwtUlb3i62UE6Xw1vDEsVq2uWg4PYfBcY="
APP_PASSWORD = "1234"
UPLOAD_DIR = "/app/uploads"
HOSTNAME = "0.0.0.0"
PORT = "8080"

[deploy]
startCommand = "node node_modules/prisma/build/index.js migrate deploy && node prisma/seed-categorias.js && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
